### ISSUE TITLE
[refactor] test refactor for clarity

### ISSUE THREAD

**Issue by weswalla** [neighbour-hoods/sensemaker-lite#66]
The current test suite is not well structured and could be improved to make use of jest features like `beforeAll` as there are many common setups across the tests.

The tests should also be restructured to be a coherent entry point for contributors to understand what the sensemaker does.

**Comment by weswalla** [comment]
we also have a ton of unnecessary set up of primitives that occur redundantly. We can clean up a lot of those simply by mocking `EntryHash`es of the dependent primitives (for example, dimension eh on an assessment). The test naming and ordering could be refactored to be more clear as well.

**Comment by adaburrows** [comment]
It's more than just a ton of redundant setup, it's that many of the tests across the different files are actually redundant. I'm not sure why they were written this way, but the [largest file with the most tests has all (or almost all) the tests in all the other files, too](https://github.com/neighbour-hoods/sensemaker-lite/blob/develop/tests/src/sensemaker_dna/sensemaker/neighbourhood.ts).

Instead of having various scenarios that run through potentially redundant portions of setup for various end-user scenarios, we should just have functional tests that exercise each portion of the client library. User scenario based testing is great on the front end when one wants to check for compliance with product requirements, but it's not necessary for the testing in the library.
