### ISSUE TITLE
API to look up method to call provided an input/output dimension

### ISSUE THREAD

**Issue by adaburrows** [neighbour-hoods/sensemaker-lite#68]
Add an API to the sensemaker that takes an output dimension and looks up with method is used to compute that dimension.

The API:
- [x] given an input dimension EH, should return a list of method objects which have the corresponding input.
- [x] given an output dimension EH, should return a list of method object which have the output dimension.
- [x] given no filter return all methods

**Comment by weswalla** [comment]
I think if we switched over to #73 then this could just be a sensemaker store method rather than a zome method

**Comment by pospi** [comment]
Awaiting completion of #73 since that will create the necessary link structures for being able to retrieve `Methods` in bulk without starting from an `AppletConfig`.

Just a note that this may imply some performance considerations down the track if it is used in automatic Method execution. Would we necessarily want the Sensemaker recomputing Assessment data for Applets which are not currently loaded and in view? Or is this advantageous, since it ensures that cross-application data is synced to peers as soon as it becomes stale?

**Comment by adaburrows** [comment]
> Just a note that this may imply some performance considerations down the track if it is used in automatic Method execution. Would we necessarily want the Sensemaker recomputing Assessment data for Applets which are not currently loaded and in view? Or is this advantageous, since it ensures that cross-application data is synced to peers as soon as it becomes stale?

This is a temporary stopgap until we implement something more suitable. It is also for use during configuration in the dimension configuration screen.
