### ISSUE TITLE
Test suite does not execute on CI

### ISSUE THREAD

**Issue by pospi** [neighbour-hoods/sensemaker-lite#80]
Manifests on latest `develop` as:

    Invalid lair server version, this client requires '0.2.3', but got '0.3.0'.

**Comment by pospi** [comment]
I think this is a sign of incompatibility in the Holonix environment we're using. The last update to the Nix env was 544f551 in April. @weswalla can I presume the tests were running when you updated? Possibly the `lair` version was not pinned and a more recent one has since become available.

**Comment by weswalla** [comment]
it still runs for me on my computer

**Comment by adaburrows** [comment]
Please see that all tests have been failing [for a while now](https://github.com/neighbour-hoods/sensemaker-lite/actions/runs/6858761229/job/18650017927#step:5:3395), all because we are running out of disk space on our test runner from having to build everything. I presume Holochain doesn't want to pay to keep old built versions of Holochain they don't support available to download. I'll go ahead and merge, since it helps run tests locally. However, we may be forced to upgrade Holochain just to make sure we don't need to build everything on a GitHub worker.

**Comment by adaburrows** [comment]
We're using an outdated version of Holochain. I'm not sure what we need to change to upgrade, but I do know it breaks (I've tried it). Presumably it's all in the Holochain change log. Also, if we want to update to versions not in any of the Nix Flake version files, we'll have to make our own version config that pins the correct versions like the ones in the Holochain repo: https://github.com/holochain/holochain/tree/develop/versions

We also need to fix our flake file since it doesn't seem to be controlling for which version of tsc we are using and potentially other dependencies, which would explain why Nick can compile his code, while we can't compile the same code without getting compile time errors.

**Comment by pospi** [comment]
Adjusted title since this is now only affecting CI due to the remaining disk space issue.

The flake file shouldn't be the case of a mismatched `tsc` version but rather NPM / PNPM's package lock files, no? In any case I think I may have fixed this in the commits I'm about to cherry-pick for #66... let's see...

**Comment by pospi** [comment]
Yep typescript should be fine in tests once c3e8fe5 is merged.

**Comment by adaburrows** [comment]
Test suite works fine in CI and local dev envs. Closing.
